# config/indicators_contract.yaml
# 契约：与 docs/contracts/03. 指标数据契约（步骤2 · Alt-Flow）v1.1 同步
version: "step2-contract-v1.1"
akshare_version: "1.17.40"

defaults:
  tz: "Asia/Shanghai"
  windows: ["10:00", "14:00"]
  topN: 20                           # 用于成交额集中度的前 N（默认 20）
  units:
    turnover: "yuan"                 # 成交额口径（元）
    margin: "yi_yuan"                # 两融金额统一到“亿元”

symbols:
  index_sh: "sh000001"               # 上证指数（固定映射）
  index_hs300: "sh000300"            # 沪深300（固定映射）
  index_hs300_alt: "csi000300"       # 等价替代符号（如环境仅提供 CSI 代码）

# 指标定义（机器可读映射）
# 说明：
# - role: gate（直接参与闸门布尔判定）| derived（用于派生/展示，不直接判定）| background（仅背景记录）| flag | system
# - comparator: gte/lte/eq/none（none 表示不直接比较）
# - threshold_key: 从配置中读取的阈值键；无则 null
# - required: 此指标是否必须产生（对本窗口）
# - intraday_required: 是否属于“盘中关键项”（缺失则直接判定失败，触发 intraday_missing）
# - windows: 生效窗口；若为空数组或省略，表示不限定（一般用于背景项）
# - sources: 数据来源优先级（首选 → 备用）
indicators:

  limit_up_count:
    role: gate
    unit: "count"
    comparator: "gte"
    threshold_key: "emotion_gate.limit_up_count_min"
    required: true
    intraday_required: true
    windows: ["10:00", "14:00"]
    sources:
      - "stock_zt_pool_em"
      - "stock_zt_pool_previous_em"     # 回溯校验（非硬依赖）
      - "stock_zt_pool_strong_em"       # 结构侧写（备用）

  limit_down_count:
    role: derived
    unit: "count"
    comparator: "none"
    threshold_key: null
    required: true
    intraday_required: true
    windows: ["10:00", "14:00"]
    sources:
      - "stock_zt_pool_dtgc_em"

  limitup_down_ratio:
    role: gate
    unit: "ratio"
    comparator: "gte"
    threshold_key: "emotion_gate.limitup_down_ratio_min"
    required: true
    intraday_required: true
    windows: ["10:00", "14:00"]
    sources:
      - "stock_zt_pool_em"
      - "stock_zt_pool_dtgc_em"

  turnover_concentration_top20:
    role: gate
    unit: "ratio"                       # 0..1
    comparator: "lte"
    threshold_key: "emotion_gate.turnover_concentration_max"
    required: true
    intraday_required: true
    windows: ["10:00", "14:00"]
    sources:
      - "stock_zh_a_spot_em"
      - "stock_sh_a_spot_em"
      - "stock_sz_a_spot_em"
      - "stock_bj_a_spot_em"
      - "stock_zh_a_hist_min_em"        # 回退复算
      - "stock_intraday_em"
      - "stock_intraday_sina"
    fallback_note: "分钟线 1 分粒度通常仅近 5 个交易日有效；回退命中须记录到 indicators.sources"

  hs300_vol_30d_annualized:
    role: derived
    unit: "annualized_vol"              # 小数，例如 0.22 表示 22% 年化
    comparator: "none"
    threshold_key: null
    required: true
    intraday_required: false
    windows: []                         # 日终口径；用于计算分位，不直接比较
    sources:
      - "stock_zh_index_daily_em"       # symbol: sh000300 / csi000300
      - "index_zh_a_hist"

  vol_percentile:
    role: gate
    unit: "percentile"                  # 0..1
    comparator: "lte"
    threshold_key: "emotion_gate.vol_percentile_max"
    required: true
    intraday_required: false
    windows: ["10:00", "14:00"]         # 判定时读取最近可得的分位
    sources:
      - "stock_zh_index_daily_em"
      - "index_zh_a_hist"

  sh_above_ma20:
    role: gate
    unit: "boolean"
    comparator: "eq"
    threshold_key: "emotion_gate.ma20_required"   # bool
    required: true
    intraday_required: true
    windows: ["10:00", "14:00"]
    sources:
      - "stock_zh_index_daily_em"       # 计算 MA20（昨收）
      - "stock_zh_index_spot_em"        # 当日实时价对比
      - "stock_zh_index_spot_sina"

  margin_net_repay_yi_prev:
    role: background
    unit: "yi_yuan"
    comparator: "none"                   # 不参与当日布尔判定
    threshold_key: null
    required: true
    intraday_required: false
    windows: []                          # 上一交易日 EOD
    sources:
      - "stock_margin_sse"               # 区间：start_date/end_date（YYYYMMDD）
      - "stock_margin_szse"              # 单日：date（YYYYMMDD）
      - "stock_margin_detail_sse"
      - "stock_margin_detail_szse"
      - "stock_margin_underlying_info_szse"

  intraday_missing:
    role: flag
    unit: "boolean"
    comparator: "eq"                     # 期望为 False
    expected: false
    threshold_key: null
    required: true
    intraday_required: true
    windows: ["10:00", "14:00"]
    sources: []                          # 由采集器/聚合器内部判定

  calendar_degraded:
    role: flag
    unit: "boolean"
    comparator: "none"                   # 记录用，不单独否决
    threshold_key: null
    required: true
    intraday_required: false
    windows: []
    sources: []                          # 由调度器填写（calendar 缓存/回退状态）

  window:
    role: system
    unit: "string"
    comparator: "none"
    threshold_key: null
    required: true
    intraday_required: false
    windows: []
    sources: []                          # 由调度器填写

  tz:
    role: system
    unit: "string"
    comparator: "none"
    threshold_key: null
    required: true
    intraday_required: false
    windows: []
    sources: []                          # 由调度器/配置填写

  calc_at:
    role: system
    unit: "datetime_iso8601_+08:00"
    comparator: "none"
    threshold_key: null
    required: true
    intraday_required: false
    windows: []
    sources: []                          # 指标计算完成时间

# 判定汇总（可选：供实现读取；等价于契约 §3）
decision:
  logic: "all_pass_and_no_intraday_missing"
  gates:
    - indicator: "limit_up_count"
      comparator: "gte"
      threshold_key: "emotion_gate.limit_up_count_min"
    - indicator: "limitup_down_ratio"
      comparator: "gte"
      threshold_key: "emotion_gate.limitup_down_ratio_min"
    - indicator: "turnover_concentration_top20"
      comparator: "lte"
      threshold_key: "emotion_gate.turnover_concentration_max"
    - indicator: "vol_percentile"
      comparator: "lte"
      threshold_key: "emotion_gate.vol_percentile_max"
    - indicator: "sh_above_ma20"
      comparator: "eq"
      threshold_key: "emotion_gate.ma20_required"
  hard_fail_on:
    - indicator: "intraday_missing"
      expected: false

# 事件字段（顶层必填集；用于落库与测试强校验）
event_payload_required_keys:
  - "window"
  - "tz"
  - "passed"
  - "reasons"
  - "calendar"
  - "sources"
  - "indicators"
  - "thresholds"
  - "version"
  - "calc_at"        # ← 已加入：顶层必填，与 03A/03 v1.1 对齐

# 指标字段（indicators 内的必填键；与 03 v1.1 §1 的 required:true 对齐）
indicators_required_keys:
  - "limit_up_count"
  - "limit_down_count"
  - "limitup_down_ratio"
  - "turnover_concentration_top20"
  - "hs300_vol_30d_annualized"
  - "vol_percentile"
  - "sh_above_ma20"
  - "margin_net_repay_yi_prev"
  - "intraday_missing"
  - "calendar_degraded"

# 说明补充
notes:
  - "两融金额统一以亿元记录，若源为元需除以 1e8。"
  - "MA20 使用日线收盘计算；窗口判定与昨收MA20比对，避免前视偏差。"
  - "分钟线 1 分粒度通常仅近 5 个交易日有效；回退命中须记录到 indicators.sources。"
